{
 "title": "Elasticsearch",
 "description": "Elasticsearch detailed dashboard",
 "tags": [
  "elasticsearch",
  "App"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(elasticsearch_cluster_health_status,cluster)"
   },
   {
    "name": "node",
    "label": "node",
    "query": "label_values(elasticsearch_cluster_health_up,instance)"
   },
   {
    "name": "copy_of_cluster",
    "label": "Instance",
    "query": "label_values(elasticsearch_cluster_health_status,cluster)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster health status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_status{color=\"green\",cluster=~\"$cluster\"})*0 + max(elasticsearch_cluster_health_status{color=\"yellow\",cluster=~\"$cluster\"})*1 + max(elasticsearch_cluster_health_status{color=\"red\",cluster=~\"$cluster\"})*2"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_number_of_nodes)"
    }
   ]
  },
  {
   "title": "Data nodes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_number_of_data_nodes{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Pending tasks",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_number_of_pending_tasks{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Cluster CPU Number",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_process_cpu_percent"
    }
   ]
  },
  {
   "title": "Total Cluster Ram",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$node\",job=\"node\"})"
    }
   ]
  },
  {
   "title": "Total ElasticSearch disk Size",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(elasticsearch_filesystem_data_size_bytes) by (cluster)"
    }
   ]
  },
  {
   "title": "Cluster Disk",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_filesystem_data_free_bytes / elasticsearch_filesystem_data_size_bytes * 100"
    }
   ]
  },
  {
   "title": "Total Cluster Load",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(elasticsearch_os_load1)" }
   ]
  },
  { "title": "Shards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "active primary shards",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "repeat": "shard_type",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_active_primary_shards)"
    }
   ]
  },
  {
   "title": "active shards",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_active_shards{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "initializing shards",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_initializing_shards{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "relocating shards",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_relocating_shards{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "unassigned shards",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_delayed_unassigned_shards{cluster=\"$cluster\"})"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Disk Free % $node",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 10 },
   "repeat": "node",
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "elasticsearch_filesystem_data_free_bytes{instance=\"$node\"} / elasticsearch_filesystem_data_size_bytes{instance=\"$node\"} * 100"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent", "label": "CPU usage" }
   ],
   "targets": [
    {
     "expr": "avg(elasticsearch_process_cpu_percent) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/sec" }
   ],
   "targets": [
    {
     "expr": "avg(irate(elasticsearch_transport_tx_size_bytes_total{cluster=\"$cluster\",instance=~\"$node\"}[$interval])) by (instance)",
     "legendFormat": "Out {{instance}}"
    },
    {
     "expr": "avg(irate(elasticsearch_transport_rx_size_bytes_total{cluster=\"$cluster\",instance=~\"$node\"}[$interval])) by (instance)",
     "legendFormat": "in {{instance}}"
    }
   ]
  },
  { "title": "Documents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Documents count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "Documents" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_indices_docs) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Documents indexed rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "index calls/s" }
   ],
   "targets": [
    {
     "expr": "max(irate(elasticsearch_indices_indexing_index_total[$interval])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Documents deleted rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "Documents/s" }
   ],
   "targets": [
    {
     "expr": "max (rate(elasticsearch_indices_docs_deleted[$interval]))  by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Documents merged rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "Documents/s" }
   ],
   "targets": [
    {
     "expr": "max( rate(elasticsearch_indices_merges_total{cluster=\"$cluster\",name=~\"$node\"}[$interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Total Operations stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Total Operations  rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short", "label": "Operations/s" }
   ],
   "targets": [
    {
     "expr": "sum(max(irate(elasticsearch_indices_indexing_index_total[$interval]))  by (instance))",
     "legendFormat": "indexing"
    },
    {
     "expr": "sum(max(irate(elasticsearch_indices_search_query_total[$interval])) by (instance))",
     "legendFormat": "query"
    },
    {
     "expr": "sum(max( irate(elasticsearch_indices_search_fetch_total[$interval])) by (instance))",
     "legendFormat": "fetch"
    },
    {
     "expr": "sum(max (irate(elasticsearch_indices_merges_total[$interval]))  by (instance))",
     "legendFormat": "merges"
    },
    {
     "expr": "irate(elasticsearch_indices_refresh_total{cluster=\"$cluster\",name=~\"$node\"}[$interval])",
     "legendFormat": "{{ name }} - refresh"
    },
    {
     "expr": "sum(max(irate(elasticsearch_indices_flush_total[$interval])) by (instance))",
     "legendFormat": "flush"
    }
   ]
  },
  {
   "title": "Total Operations  time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "ms", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "max(irate(elasticsearch_indices_indexing_index_time_seconds_total[$interval])) by (instance)",
     "legendFormat": "{{ instance }} index time"
    },
    {
     "expr": "max(irate(elasticsearch_indices_search_query_time_ms_total[$interval])) by (instance)",
     "legendFormat": "{{ instance }} - query"
    },
    {
     "expr": "max(irate(elasticsearch_indices_search_fetch_time_ms_total[$interval])) by (instance)",
     "legendFormat": "{{ instance }} - fetch"
    },
    {
     "expr": "max(irate(elasticsearch_indices_merges_total_time_ms_total[$interval])) by (instance)",
     "legendFormat": "{{ instance }} - merges"
    },
    {
     "expr": "max(irate(elasticsearch_indices_refresh_total_time_ms_total[$interval])) by (instance)",
     "legendFormat": "{{ instance }} - refresh"
    },
    {
     "expr": "max(irate(elasticsearch_indices_flush_time_ms_total[$interval])) by (instance)",
     "legendFormat": "{{ instance }} - flush"
    }
   ]
  },
  { "title": "Times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Query time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "ms", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "max(rate(elasticsearch_indices_search_query_time_seconds[$interval])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Indexing time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 48 },
   "yaxes": [
    { "format": "ms", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "max(rate(elasticsearch_indices_indexing_index_time_seconds_total[$interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Merging time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 48 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "max(rate(elasticsearch_indices_merges_total_time_seconds_total[$interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Caches", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Field data memory size",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_indices_fielddata_memory_size_bytes) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Field data evictions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 59 },
   "yaxes": [
    { "format": "short", "label": "Evictions/s" }
   ],
   "targets": [
    {
     "expr": "max (rate(elasticsearch_indices_fielddata_evictions[$interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Query cache size",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "bytes", "label": "Size" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_indices_query_cache_memory_size_bytes) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Query cache evictions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 59 },
   "yaxes": [
    { "format": "short", "label": "Evictions/s" }
   ],
   "targets": [
    {
     "expr": "max(rate(elasticsearch_indices_query_cache_evictions[$interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Thread Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Thread Pool operations rejected",
   "type": "graph",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " max(irate(elasticsearch_thread_pool_rejected_count[$interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Thread Pool operations queued",
   "type": "graph",
   "gridPos": { "h": 13, "w": 6, "x": 6, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_thread_pool_active_count) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Thread Pool threads active",
   "type": "graph",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(elasticsearch_thread_pool_active_count) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Thread Pool operations completed",
   "type": "graph",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(irate(elasticsearch_thread_pool_completed_count[$interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "JVM Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "short", "label": "GCs" }
   ],
   "targets": [
    {
     "expr": "max(rate(elasticsearch_jvm_gc_collection_seconds_count[$interval])) by (instance)",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "GC time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "max(rate(elasticsearch_jvm_gc_collection_seconds_count[$interval])) by (instance)",
     "legendFormat": "{{instance}} - {{gc}}"
    }
   ]
  }
 ]
}