{
 "title": "Memcache",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "node",
    "query": "label_values(memcached_up, instance)"
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "15s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Sysytem $node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "node" },
  {
   "title": "Used RAM Memory",
   "type": "singlestat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable{instance=~\"$node\"} * 100) / node_memory_MemTotal{instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(((count(count(node_cpu{instance=~\"$node\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu{mode='idle',instance=~\"$node\"}[5m])))) * 100) / count(count(node_cpu{instance=~\"$node\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU System Load (1m avg)",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together (1 min average)",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_load1{instance=~\"$node\"}) /  count(count(node_cpu{instance=~\"$node\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Memcached Max Memory Allocation %",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together (1 min average)",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "memcached_malloced_bytes{instance=\"$node\"} / memcached_limit_bytes{instance=\"$node\"} * 100"
    }
   ]
  },
  {
   "title": "network receive",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "instance:node_network_receive_bytes:rate:sum{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "network transmit",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "instance:node_network_transmit_bytes:rate:sum{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Latenza ICPM - $node",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=~\"$node\",job=\"blackbox-ping\"}"
    }
   ]
  },
  { "title": "Memcache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Memcache Command Total %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sort(sum(sum(memcached_commands_total) by (command) / ignoring(command) group_left() sum(memcached_commands_total)) by (command) * 100)",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Memcache Command",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(memcached_commands_total[$interval])) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(irate(memcached_commands_total{command=\"set\"}[$interval])) by (instance)",
     "legendFormat": "{{instance}} - set"
    },
    {
     "expr": "sum(irate(memcached_commands_total{command=\"get\"}[$interval])) by (instance)",
     "legendFormat": "{{instance}} -get"
    }
   ]
  },
  {
   "title": "Memcache Command",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(memcached_commands_total{command=~\"get|set|delete\"}[$interval])",
     "legendFormat": "{{instance}} - set"
    },
    {
     "expr": "irate(memcached_commands_total{command=~\"get|set|delete\"}[$interval])",
     "legendFormat": "{{instance}} -get"
    }
   ]
  },
  {
   "title": "% Hit ratio",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum (memcached_commands_total{instance=~\"$node\", status=\"miss\"})  / sum (memcached_commands_total{instance=~\"$node\"})",
     "legendFormat": "hit ratio"
    }
   ]
  },
  {
   "title": "Networks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(sum(instance:node_network_receive_bytes:rate:sum{instance=~\"$node\"}) by (instance) * -1 )",
     "legendFormat": "{{instance}} - Received"
    },
    {
     "expr": "sum(instance:node_network_transmit_bytes:rate:sum{instance=~\"$node\"}) by (instance)",
     "legendFormat": "{{instance}} - Trasmit "
    }
   ]
  },
  {
   "title": "Items",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(memcached_items_total[30s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "memcached items evicted",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(memcached_items_evicted_total[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "memcached_limit_bytes", "legendFormat": "{{ instance }} Limit" },
    { "expr": "memcached_malloced_bytes", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "MCrouter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "MC Router Clients",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "mcrouter_clients", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "MC Command Count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(mcrouter_command_count[60s])) by (cmd,instance)",
       "legendFormat": "{{instance}} - {{cmd}}"
      }
     ]
    },
    {
     "title": "MC Router Command %",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum (mcrouter_commands > 0) by (cmd)\n/ ignoring(cmd) group_left\nsum (mcrouter_commands >0)) * 100"
      }
     ]
    },
    {
     "title": "MC Router Command %",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum (mcrouter_commands > 0) by (cmd)\n/ ignoring(cmd) group_left\nsum (mcrouter_commands >0)) * 100"
      }
     ]
    }
   ]
  }
 ]
}